default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: ""
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: analysis
  # database: phantom_2015_11_13

